version: "3.5"

volumes:
  db_data:
    driver: local

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: "echo stat | nc localhost $$ZOOKEEPER_CLIENT_PORT"
      start_period: 30s

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      start_period: 30s

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.1.0
    container_name: kafka-rest-proxy
    restart: unless-stopped
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_REST_HOST_NAME: "kafka-rest-proxy"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000
    healthcheck:
      test: "curl -f http://localhost:8082 || exit 1"
      start_period: 30s

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    container_name: kafka-topics-ui
    restart: unless-stopped
    depends_on:
      - kafka-rest-proxy
    ports:
      - "8085:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082"
      PROXY: "true"
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:8000 || exit 1"
      start_period: 30s

  falcon-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: falcon
      MYSQL_USER: falcon
      MYSQL_PASSWORD: falcon

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - falcon-db:falcon-db
    depends_on:
      - falcon-db
    ports:
      - 9191:80
    environment:
      MYSQL_USERNAME: falcon
      MYSQL_ROOT_PASSWORD: falcon
      PMA_HOST: falcon-db

  falcon-consumer:
    image: docker.falcon.com/falcon-task-consumer:latest
    container_name: falcon-consumer
    depends_on:
      - kafka-topics-ui
      - falcon-db
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_GROUP_ID: "falcon-group"
      TOPICS: "falcon-1"

  falcon-producer:
    image: docker.falcon.com/falcon-task-producer:latest
    ports:
      - "8080:8080"
    container_name: falcon-producer
    depends_on:
      - falcon-consumer
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      INITIAL_DELAY: 30000
      INTERVAL: 3000
      TOPICS: "falcon-1"

  falcon-view:
    image: docker.falcon.com/falcon-task-view:latest
    container_name: falcon-view
    ports:
      - "8081:8080"
    depends_on:
      - falcon-db
