spring:
  kafka.producer:
    bootstrap-servers: kafka:9092
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    port: 9092
    advertised.host.name: kafka

app:
  camel:
    direct:
      validate-falcon: validateFalconMessage
    kafka:
      component: "kafka:${app.topic.falcon}?brokers=${spring.kafka.producer.bootstrap-servers}&serializerClass=org.apache.kafka.common.serialization.StringSerializer"
      async:
        route: sendAsyncToKafka
  topic:
    falcon: falcon-1