spring:
  kafka.consumer:
    bootstrap-servers: kafka:9092
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    port: 9092
    advertised.host.name: kafka
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://falcon-db:3306/falcon
    username: falcon
    password: falcon
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  h2:
    console:
      enabled: true
      path: /console

app:
  camel:
    direct:
      validate-falcon: validateFalconMessage
    kafka:
      component: "kafka:${app.topic.falcon}?brokers=${spring.kafka.consumer.bootstrap-servers}&serializerClass=org.apache.kafka.common.serialization.StringSerializer"
  topic:
    falcon: falcon-1